Revert "VolumeDialog: Ensure proper resource release"
This reverts commit b83e3314ab1a9cb0da5ed812f5abfc38dd7b5423.

Log:

FATAL EXCEPTION: main
Process: com.android.systemui, PID: 990
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.LayoutInflater android.app.Dialog.getLayoutInflater()' on a null object reference
 at com.android.systemui.volume.VolumeDialogImpl.initRow(VolumeDialogImpl.java:997)
 at com.android.systemui.volume.VolumeDialogImpl.addRow(VolumeDialogImpl.java:931)
 at com.android.systemui.volume.VolumeDialogImpl.onStateChangedH(VolumeDialogImpl.java:2311)
 at com.android.systemui.volume.VolumeDialogImpl$10.onStateChanged(VolumeDialogImpl.java:2810)
 at com.android.systemui.volume.VolumeDialogControllerImpl$C$3.run(VolumeDialogControllerImpl.java:965)
 at android.os.Handler.handleCallback(Handler.java:958)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8190)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)