Fix missing private boolean mBatteryHidden in BatteryMeterViewController.java
This fixes :

frameworks/base/packages/SystemUI/src/com/android/systemui/battery/BatteryMeterV
iewController.java:118: error: cannot find symbol
mView.setVisibility(!batteryPresent || mBatteryHidden
^
symbol: variable mBatteryHidden