java.lang.NullPointerException: name is null
https://issuetracker.google.com/issues/63746837

Test: null

Change-Id: I7f906152f64c67f9a33dcd32eac4fe3fc918b9d4
Signed-off-by: liangweikang@xiaomi.com <liangweikang@xiaomi.com>
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>