widget: Fix DateTimeView fc issue
In one process, we can add more than one DateTimeView, but registerReceiver only once.
If register context cannot match unregister context, then FC occured.

Exception info:
java.lang.IllegalArgumentException: Receiver not registered:android.widget.DateTimeView$ReceiverInfo

For Example:
There are two packages run in systemui process,
and ActivityThread.mInitialApplication is not initialized by systemui package.
1.add DateTimeView A(view's getApplicationContext is SystemUIService) and registerReceiver.
2.add DateTimeView B(view's getApplicationContext is null).
3.remove DateTimeView A.
4.remove DateTimeView B and try to unregisterReceiver.
5.FC occured.

Solution:
getApplicationContextIfAvailable should return unique Context in one process.

Change-Id: I27f223f00822079f72442abfd283b366d313fa62
Signed-off-by: longhai <longhai@xiaomi.com>
Signed-off-by: neobuddy89 <neobuddy89@gmail.com>